//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDashboard.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        public int Код { get; set; }
        public Nullable<int> КодПерсонала { get; set; }
        public Nullable<int> КодЭВМ { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Описание { get; set; }
        public Nullable<System.DateTime> ДатаРемонта { get; set; }
        public string Ремонт { get; set; }
        public string Результат { get; set; }
    
        public virtual ЭВМ ЭВМ { get; set; }
        public virtual Персонал Персонал { get; set; }
    }
}
